# Sample qBraid environment configuration
name: "My Environment"
description: "Example qBraid environment for demonstration purposes"
tags:
  - "qbraid"
  - "environment"
  - "example"
icon: "icon.png"
python_version: "3.11.6"
kernel_name: "Python 3 [MyEnv]"
shell_prompt: "my-env"
python_packages:
  pyqasm: ">=0.3.0"
  matplotlib: ""