name: Publish Environment on qBraid

on:
  workflow_dispatch:

jobs:
  publish_env:
    runs-on: ubuntu-latest 
    steps:
      - name: Publish Environment
        uses: qBraid/publish-environment-action@v1
        with:
          api-key: ${{ secrets.QBRAID_API_KEY }}
          environment-file: .qbraid.yaml
          wait-for-completion: false
          persist-env: false